$(document).ready(function () {

    var language = sessionStorage.getItem('language');

    $('#english').on('click', function () {
        sessionStorage.setItem('language', 'enUS');
        window.location.reload();
    });

    $('#spanish').on('click', function () {
        sessionStorage.setItem('language', 'esES');
        window.location.reload();
    });

    if (language != undefined) {
        setLanguageByLang(language)
    }
    else
    {
        sessionStorage.setItem('language', 'esES');
        language = sessionStorage.getItem('language');
        setLanguageByLang(language);
    }
});

function setLanguageByLang(lang) {

    var dictionary = '{'
        + '"translations": ['
        +   '{'
        +       '"class": "trl-web-title",'
        +       '"enUS": "Path of ascension - Camera & control",'
        +       '"esES": "Path of ascension - Control y camara"'
        +   '},'
        +   '{'
        +       '"class": "trl-menu-1",'
        +       '"enUS": "Home",'
        +       '"esES": "Inicio"'
        +   '},'
        +   '{'
        +       '"class": "trl-menu-2",'
        +       '"enUS": "About me",'
        +       '"esES": "Sobre mi"'
        +   '},'
        +   '{'
        +       '"class": "trl-characters",'
        +       '"enUS": "Characters",'
        +       '"esES": "Personajes"'
        +   '},'
        +   '{'
        +       '"class": "trl-camera",'
        +       '"enUS": "Camera",'
        +       '"esES": "Camara"'
        +   '},'
        +   '{'
        +       '"class": "trl-controls",'
        +       '"enUS": "Controls",'
        +       '"esES": "Controles"'
        +   '},'
        +   '{'
        +       '"class": "trl-title",'
        +       '"enUS": "Camera & control",'
        +       '"esES": "Control y camara"'
        +   '},'
        +   '{'
        +       '"class": "trl-press-key",'
        +       '"enUS": "Press a key",'
        +       '"esES": "Presiona una tecla"'
        +   '},'
        +   '{'
        +       '"class": "trl-camera-p-1",'
        +       '"enUS": "The game has a third-person camera and the player can control it at will with certain conditions and limitations:",'
        +       '"esES": "El juego tiene una camara en tercera persona y puede controlarla el jugador a su antojo con ciertas condiciones y limitaciones:"'
        +   '},'
        +   '{'
        +       '"class": "trl-camera-p-2",'
        +       '"enUS": "The rotation of the character is relative to the camera as long as the character is moving, otherwise the camera can rotate around the character without any problem. The camera position it is changed with the mouse.",'
        +       '"esES": "La rotación del personaje es relativo a la camara siempre y cuando el personaje se este moviendo, en caso contrario la camara podra girar al rededor del personaje sin ningún problema. La posición de la camara se cambia utilizando el ratón."'
        +   '},'
        +   '{'
        +       '"class": "trl-camera-p-3",'
        +       '"enUS": "The proximity and distance of the camera are limited, these limits cannot be modified since they are expressly designed so that the camera does not enter into the character model and does not move away showing more information than it should. This position it is changed with the mouse wheel",'
        +       '"esES": "La cercania y lejanía de la camara están limitadas, estos limites no se podrán modificar ya  que están pensados expresamente para que la camara no entre dentro del modelo del personaje y no se aleje mostrando más información de la que deberia. Esta posicion se cambiara con la rueda del ratón."'
        +   '},'
        +   '{'
        +       '"class": "trl-camera-p-4",'
        +       '"enUS": "When there are obstacles in between, the camera will approach the character giving a feeling of collision with the environment so that the character can be kept visible all the time.",'
        +       '"esES": "Cuando hayan obstaculos de por medio la camara se acercará al personaje dando una sensación de colisión con el entorno para que se pueda mantener el personaje todo el tiempo visible."'
        +   '},'
        +   '{'
        +       '"class": "trl-movement",'
        +       '"enUS": "Movement",'
        +       '"esES": "Movimiento"'
        +   '},'
        +   '{'
        +       '"class": "trl-movement-list",'
        +       '"enUS": "Movement:",'
        +       '"esES": "Movimiento:"'
        +   '},'
        +   '{'
        +       '"class": "trl-preview",'
        +       '"enUS": "Preview",'
        +       '"esES": "Vista previa"'
        +   '},'
        +   '{'
        +       '"class": "trl-movement-p-1",'
        +       '"enUS": "The direction of the character is controlled with the WASD keys and the jump with spacebar. Since you cannot control the intensity with which the keys are pressed on a keyboard, the mouse is used to support the rotation of the character in case it is already moving.",'
        +       '"esES": "La dirección del personaje se controla con las teclas WASD y el salto con el espacio. Ya que en un teclado no se puede controlar la intensidad con la que se pulsan las teclas se utiliza el ratón para apoyar la rotación del personaje en caso de que ya se esté desplazando."'
        +   '},'
        +   '{'
        +       '"class": "trl-movement-p-2",'
        +       '"enUS": "As for the displacement speed, it is controlled in a combination of rotational force and movement force. This combination of forces from a certain value will be able to change the character between three states, standing, walking and running.",'
        +       '"esES": "En cuanto a la velocidad de desplazamiento se controla en una combinación de fuerza de rotación y fuerza de movimiento. Esta combinación de fuerzas a partir de cierto valor podrá cambiar el personaje entre tres estados, parado, caminando y corriendo. "'
        +   '},'
        +   '{'
        +       '"class": "trl-movement-p-3",'
        +       '"enUS": "This means that depending on the combination of keys and rotation, the speed and the states will change.",'
        +       '"esES": "Esto significa que en función de la combinación de teclas y rotación la velocidad y los estados irán cambiando."'
        +   '},'
        +   '{'
        +       '"class": "trl-movement-p-4",'
        +       '"enUS": "As for the position of the camera, we can change it by moving the mouse and the closeness and distance of the camera with the mouse wheel.",'
        +       '"esES": "En cuanto a la posición de la camara la podemos cambiar moviendo el ratón y la cercanía y la lejanía de la camara con la rueda del ratón."'
        +   '},'
        +   '{'
        +       '"class": "trl-skill-p-1",'
        +       '"enUS": "The buttons that are used to launch skills. Q to cast the basic ability and E to cast the powerful ability.",'
        +       '"esES": "Los botones que se utilizan para lanzar las habilidades. Q para lanzar la habilidad básica y E para lanzar la habilidad poderosa."'
        +   '},'
        +   '{'
        +       '"class": "trl-pause-p-1",'
        +       '"enUS": "The pause button releases the pointer and disables camera movement with the mouse and will pause the game so that the desired menu option can be selected without any problem.",'
        +       '"esES": "El botón de pausa libera el puntero y deshabilita el movimiento de la cámara con el ratón y pausará el juego para que se pueda seleccionar la opción deseada del menú sin problemas."'
        +   '},'
        +   '{'
        +       '"class": "trl-attack-p-1",'
        +       '"enUS": "The attack is located on the left button of the mouse since greater precision is necessary when attacking so that the attack can be redirected at any time simply by moving the mouse.",'
        +       '"esES": "El ataque está situado en el botón izquierdo del ratón ya que es necesario una mayor precisión cuando se ataca de forma que se pueda redirigir el ataque en cualquier momento simplemente moviendo el ratón."'
        +   '},'
        +   '{'
        +       '"class": "trl-attack-p-2",'
        +       '"enUS": "Each time we press the left mouse button, the character will perform an attack, this attack has three combos which increase the strength of the attack for each time we chain one attack with another up to a maximum of 3 combos.",'
        +       '"esES": "Cada vez que pulsamos el botón izquierdo del ratón  el personaje realizará un ataque, este ataque tiene tres combos los cuales incrementan la fuerza del ataque por cada vez que encadenemos un ataque con otro hasta un máximo de 3 combos."'
        +   '},'
        +   '{'
        +       '"class": "trl-block-p-1",'
        +       '"enUS": "The right button of the mouse is used to lock to make it more intuitive when making a lock and quick action.",'
        +       '"esES": "Se utiliza el botón derecho del ratón para bloquear para que sea mas intuitivo a la hora de realizar un bloqueo y de una acción rápida."'
        +   '},'
        +   '{'
        +       '"class": "trl-buttons-description",'
        +       '"enUS": "Buttons description",'
        +       '"esES": "Descripción de los botones"'
        +   '},'
        +   '{'
        +       '"class": "trl-run-top",'
        +       '"enUS": "Run",'
        +       '"esES": "Correr"'
        +   '},'
        +   '{'
        +       '"class": "trl-skills",'
        +       '"enUS": "Skills:",'
        +       '"esES": "Habilidades:"'
        +   '},'
        +   '{'
        +       '"class": "trl-skills-top",'
        +       '"enUS": "Skills",'
        +       '"esES": "Habilidades"'
        +   '},'
        +   '{'
        +       '"class": "trl-pause-top",'
        +       '"enUS": "Pause",'
        +       '"esES": "Pausa"'
        +   '},'
        +   '{'
        +       '"class": "trl-attack-top",'
        +       '"enUS": "Attack",'
        +       '"esES": "Ataque"'
        +   '},'
        +   '{'
        +       '"class": "trl-block-top",'
        +       '"enUS": "Block",'
        +       '"esES": "Bloquear"'
        +   '},'
        +   '{'
        +       '"class": "trl-skill-p",'
        +       '"enUS": "Our character will only have two abilities with his character, the basic ability of the player will be activated with the Q key and the final ability that will be activated with the E key. In this way we allow the player to be able to launch the abilities of his character quickly without having to change hand position.",'
        +       '"esES": "Nuestro personaje solo dispondrá de dos habilidades con su personaje, la habilidad básica del jugador se accionará con la tecla Q y la habilidad final que se accionará con la tecla E. De esta forma permitimos al jugador poder lanzar las habilidades de su personaje rápidamente sin tener que cambiar la mano de posición."'
        +   '},'
        +   '{'
        +       '"class": "trl-actions",'
        +       '"enUS": "Actions:",'
        +       '"esES": "Acciones:"'
        +   '},'
        +   '{'
        +       '"class": "trl-actions-p",'
        +       '"enUS": "The character will only have two actions, one, to perform attacks that can be chained if we press repeatedly to perform more powerful attacks and the second to block these actions since they go to where the character is looking.They have been placed on the mouse, the left click It will be used to attack and the right click will be used to block, in this way we can rotate the camera with the mouse, which will allow us to have a greater precision of where to direct the blocks and the character\'s attacks.",'
        +       '"esES": "El personaje solo dispondrá de dos acciones, una, realizar ataques que se pueden encadenar si pulsamos repetidas veces para realizar ataques más poderosos y la segunda bloquear estas acciones ya que van hacia donde está mirando el personaje se han situado en el ratón, el clic izquierdo se utilizará para atacar y el clic derecho se utilizará para bloquear, de esta forma podemos girar la cámara con  el ratón lo que nos permitirá tener una mayor precisión de a donde dirigir los bloqueos y los ataques del personaje."'
        +   '},'
        +   '{'
        +       '"class": "trl-mouse",'
        +       '"enUS": "Mouse",'
        +       '"esES": "Rat\u00F3n"'
        +   '},'
        +   '{'
        +       '"class": "trl-keyboard",'
        +       '"enUS": "Keyboard",'
        +       '"esES": "Teclado"'
        +   '},'
        +   '{'
        +       '"class": "tr-english",'
        +       '"enUS": "Enlgish",'
        +       '"esES": "Ingl\u00E9s"'
        +   '},'
        +   '{'
        +       '"class": "tr-spanish",'
        +       '"enUS": "Spanish",'
        +       '"esES": "Espa\u00F1ol"'
        +   '},'
        +   '{'
        +       '"class": "trl-read-more",'
        +       '"enUS": "Read more",'
        +       '"esES": "Leer mas"'
        +   '},'
        +   '{'
        +       '"class": "trl-return",'
        +       '"enUS": "Return",'
        +       '"esES": "Volver"'
        +   '},'
        +   '{'
        +       '"class": "trl-language",'
        +       '"enUS": "Language",'
        +       '"esES": "Idioma"'
        +   '},'
        +   '{'
        +       '"class": "trl-controls-p-1",'
        +       '"enUS": "The best way to make the controls responsive to the player is by applying the same settings that the majority of games have for keyboards.",'
        +       '"esES": "La mejor forma de que los controles sean receptivos para el jugador es aplicando la misma configuración que tienen la gran mayoría de juegos para los teclados."'
        +   '},'
        +   '{'
        +       '"class": "trl-controls-p-2",'
        +       '"enUS": "The best way to explain the keyboard layout is by dividing it into different categories:",'
        +       '"esES": "La mejor forma de explicar la disposición del teclado es seccionándolo en distintas categorías:"'
        +   '},'
        +   '{'
        +       '"class": "trl-controls-p-3",'
        +       '"enUS": "The best way to make the controls responsive to the player is by applying the same settings that the majority of games have for keyboards.",'
        +       '"esES": "La mejor forma de que los controles sean receptivos para el jugador es aplicando la misma configuración que tienen la gran mayoría de juegos para los teclados."'
        +   '},'
        +   '{'
        +       '"class": "trl-william-archetype-1",'
        +       '"enUS": "As for the archetype of Carl Jung, we place William as an assistant, he helps the player in secret despite the fact that the king does not help him to improve the conditions of the elves that inhabit the region.",'
        +       '"esES": "En cuanto al arquetipo de Carl Jung, a William lo situamos como ayudante, ayuda en secreto al jugador a pesar de que el rey no le presta ayuda para poder mejorar las condiciones de los elfos que habitan en la región."'
        +   '}'
        +']'
    +'}';

    var data = JSON.parse(dictionary);

    for (var i in data.translations) {
        if (lang === "enUS") {
            $('.' + data.translations[i].class).text(data.translations[i].enUS);
        }
        else {
            $('.' + data.translations[i].class).text(data.translations[i].esES);
        }
    }
}
